version: "3.3"

services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: discord-phishing-redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  app:
    image: phamleduy04/discord-phishing-backend:latest
    container_name: discord-phishing-backend
    command: ["npm", "start"]
    env_file: .env
    environment: 
      - DOCKER=true
    networks:
      - redis-net
    depends_on:
      - redis
    ports:
      - "${PORT}:${PORT}"
    restart: always

networks:
  redis-net:

volumes:
  redis-data: