version: '3.6'

services:
  app:
    image: 'ghcr.io/phamleduy04/discord-phishing-backend'
    container_name: discord-phishing-backend
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
