version: "3.7"

services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: discord-phishing-redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  app:
    image: novelcovid/novelcovid-api:latest
    networks:
      - redis-net
    depends_on:
      - redis

networks:
  redis-net:

volumes:
  redis-data: